version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./:/app
  
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql:/val/lib/mysql
      - mysql_config:/etc/mysql
  
volumes:
  mysql:
  mysql_config:
